/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Monochrome Foundation (base - no prefix)
        'void': '#000000',
        'carbon': '#0A0908',
        'graphite': '#1A1918',
        'concrete': '#2E2C2B',
        'steel': '#4A4745',
        'aluminum': '#6B6866',
        'titanium': '#8E8B89',
        'platinum': '#B5B2B0',
        'silver': '#C9C7C5',
        'paper': '#E8E6E3',
        'raw-canvas': '#F7F5F2',
        'snow': '#FAFAF9',

        // Margiela Material (base - no prefix)
        'tabi-brown': '#4A3426',
        'stitch-white': '#FFFEF9',
        'raw-edge': '#D4D0C9',
        'exposed-seam': '#9B9691',
        'muslin': '#F0EBE3',
        'linen': '#E3DED8',
        'cotton': '#EDEAE6',
        'wool': '#D8D4CF',

        // Sacai Hybrid (base - no prefix)
        'splice-orange': '#E85D2C',
        'burnt-orange': '#CC5500',
        'layer-navy': '#1F2937',
        'deep-navy': '#0F172A',
        'hybrid-khaki': '#7C7053',
        'olive': '#556B2F',
        'contrast-olive': '#3D4F2F',
        'forest-green': '#2C4F33',

        // Laboratory Signals (base - no prefix)
        'specimen-red': '#C41E3A',
        'chemical-blue': '#0047AB',
        'petri-blue': '#4A90E2',
        'reaction-green': '#00A86B',
        'caution-amber': '#FFBF00',
        'warning-orange': '#FF6B35',

        // Subtle Accents (base - no prefix)
        'warm-beige': '#D7CCC8',
        'cool-grey': '#B0BEC5',
        'soft-taupe': '#A89F91',
        'dust-rose': '#C9ADA7',
        'sage': '#9CAF88',
        'clay': '#B7856A',

        // === MARGIELA PREFIXED COLORS ===
        'margiela-void': '#000000',
        'margiela-carbon': '#0A0908',
        'margiela-graphite': '#1A1918',
        'margiela-concrete': '#2E2C2B',
        'margiela-steel': '#4A4745',
        'margiela-aluminum': '#6B6866',
        'margiela-titanium': '#8E8B89',
        'margiela-platinum': '#B5B2B0',
        'margiela-silver': '#C9C7C5',
        'margiela-paper': '#E8E6E3',
        'margiela-raw-canvas': '#F7F5F2',
        'margiela-snow': '#FAFAF9',
        'margiela-white': '#FFFFFF',
        'margiela-off-white': '#FEFEFE',
        'margiela-pure-white': '#FFFFFF',
        'margiela-tabi-brown': '#4A3426',
        'margiela-stitch-white': '#FFFEF9',
        'margiela-raw-edge': '#D4D0C9',
        'margiela-exposed-seam': '#9B9691',
        'margiela-muslin': '#F0EBE3',
        'margiela-linen': '#E3DED8',
        'margiela-cotton': '#EDEAE6',
        'margiela-wool': '#D8D4CF',
        'margiela-white-label': '#FCFCFC',
        'margiela-number-tag': '#E0E0E0',
        'margiela-dust': '#BCB8B1',
        'margiela-cement': '#A8A29E',
        'margiela-chalk': '#F5F5F0',
        'margiela-ash-grey': '#9A9691',
        'margiela-bone': '#E3DAC9',
        'margiela-putty': '#C1B5A8',
        'margiela-slate': '#708090',
        'margiela-fog': '#D3D3D3',
        'margiela-smoke': '#848884',
        'margiela-taupe': '#483C32',
        'margiela-sage': '#9CAF88',

        // === SACAI PREFIXED COLORS ===
        'sacai-burnt-orange': '#CC5500',
        'sacai-splice-orange': '#E85D2C',
        'sacai-neon-orange': '#FF6B35',
        'sacai-layer-navy': '#1F2937',
        'sacai-deep-navy': '#0F172A',
        'sacai-midnight-navy': '#0C1220',
        'sacai-olive': '#556B2F',
        'sacai-olive-green': '#556B2F',
        'sacai-contrast-olive': '#3D4F2F',
        'sacai-forest-green': '#2C4F33',
        'sacai-ma1-green': '#3F5341',
        'sacai-bomber-sage': '#8A9A7E',
        'sacai-textile-beige': '#C9B8A3',
        'sacai-pleat-grey': '#ADB5BD',
        'sacai-ribbon-red': '#D32F2F',
        'sacai-stripe-white': '#FEFEFE',
        'sacai-layered-black': '#1C1C1C',
        'sacai-warm-beige': '#D7CCC8',
        'sacai-khaki-blend': '#8B7E66',
        'sacai-military-green': '#4B5320',
        'sacai-denim-blue': '#1560BD',
        'sacai-pinstripe-navy': '#000080',
        'sacai-oxford-blue': '#002147',
        'sacai-camel': '#C19A6B',
        'sacai-tan': '#D2B48C',
        'sacai-rust': '#B7410E',
        'sacai-maroon': '#800000',
        'sacai-burgundy': '#800020',
        'sacai-tweed-brown': '#8B7355',
        'sacai-flannel-grey': '#85929E',
        'sacai-corduroy-tan': '#D2691E',
        'sacai-wool-navy': '#1C2833',
        'sacai-silk-white': '#FFF9E6',

        // === CDG PREFIXED COLORS ===
        'cdg-absolute-black': '#000000',
        'cdg-blood-red': '#DC143C',
        'cdg-crimson': '#C41E3A',
        'cdg-charcoal': '#1A1A1A',
        'cdg-ash': '#6B6B6B',
        'cdg-void': '#000000',
        'cdg-void-grey': '#3A3A3A',
        'cdg-paper-white': '#FFFFF0',
        'cdg-industrial-white': '#F5F5F5',
        'cdg-deep-black': '#0D0D0D',
        'cdg-carbon-black': '#050505',
        'cdg-scarlet': '#FF2400',
        'cdg-ruby': '#E0115F',
        'cdg-wine': '#722F37',
        'cdg-midnight': '#191970',
        'cdg-steel-grey': '#43464B',
        'cdg-slate-black': '#2B2B2B',
        'cdg-bone-white': '#F9F6EE',
        'cdg-porcelain': '#FAFAFA',
        'cdg-deep-purple': '#5F00BA',

        // === LAB PREFIXED COLORS ===
        'lab-specimen-red': '#C41E3A',
        'lab-chemical-blue': '#0047AB',
        'lab-petri-blue': '#4A90E2',
        'lab-reaction-green': '#00A86B',
        'lab-caution-amber': '#FFBF00',
        'lab-warning-orange': '#FF6B35',
        'lab-hazard-yellow': '#FFD700',
        'lab-neon-green': '#39FF14',
        'lab-ultraviolet': '#5F00BA',
        'lab-beaker-clear': '#F0FFFF',
        'lab-culture-pink': '#FFE4E1',
        'lab-specimen-amber': '#FFBF00',
        'lab-slide-blue': '#B0E0E6',
        'lab-litmus-red': '#ED1C24',
        'lab-litmus-blue': '#0033CC',
        'lab-pipette-grey': '#C0C0C0',
        'lab-microscope-black': '#1C1C1C',
        'lab-centrifuge-silver': '#AAA9AD',
        'lab-incubator-warm': '#FFF8DC',
        'lab-biotech-cyan': '#00FFFF',
        'lab-biotech-magenta': '#FF00FF',
        'lab-biotech-yellow': '#FFFF00',
        'lab-dna-helix': '#4169E1',
        'lab-protein-purple': '#9370DB',

        // Legacy (keeping for compatibility)
        'off-black': '#0a0a0a',
        'carbon-black': '#1C1C1C',
        'concrete-gray': '#8C8C8C',
        'paper-white': '#FAFAFA',
        'safety-orange': '#FF6B35',
        'centrifuge-blue': '#0066CC',
        'petri-pink': '#FFB6C1',
        'warning-yellow': '#FFD700',
        'hazmat-green': '#00FF41',
        'glitch-red': '#FF0000',
        'glitch-cyan': '#00FFFF',
        'glitch-magenta': '#FF00FF',
        'error-green': '#00FF00',
      },
      animation: {
        'glitch': 'glitch 2s infinite',
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'spin-slow': 'spin 30s linear infinite',
        'flicker': 'flicker 0.5s infinite',
        'scan': 'scan 8s linear infinite',
        'distort': 'distort 0.3s infinite',
      },
      spacing: {
        '128': '32rem',
        '144': '36rem',
      },
      borderWidth: {
        '3': '3px',
      },
      fontFamily: {
        'helvetica': ['Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
      },
    },
  },
  plugins: [],
}